config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :residents
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resident.rb
class Resident < ApplicationRecord
  # In Rails 5, belongs_to is required by default. By adding optional: true, a resident can be added even if a room has not been assigned to them.
  belongs_to :room, optional: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :residents
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  before_action :set_resident, only: [:show, :edit, :update, :destroy]

  # Devise unthentication has been commented out as more config research is needed for controllers tests to pass.
  # To test manually, please uncomment the following line:
  # before_action :authenticate_user!

  # GET /residents
  # GET /residents.json
  def index
    @residents = Resident.all
    @rooms = Room.all
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
  end

  # GET /residents/new
  def new
    @resident = Resident.new
    @rooms = Room.all
  end

  # GET /residents/1/edit
  def edit
    @rooms = Room.all
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = Resident.new(resident_params)

    respond_to do |format|
      if @resident.save
        format.html { redirect_to residents_path, notice: 'Resident was successfully created.' }
        format.json { render :show, status: :created, location: @resident }
      else
        format.html { render :new }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residents/1
  # PATCH/PUT /residents/1.json
  def update
    respond_to do |format|
      if @resident.update(resident_params)
        format.html { redirect_to @resident, notice: 'Resident was successfully updated.' }
        format.json { render :show, status: :ok, location: @resident }
      else
        format.html { render :edit }
        format.json { render json: @resident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident.delete
    respond_to do |format|
      format.html { redirect_to residents_url, notice: 'Resident was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resident
      @resident = Resident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resident_params
      params.require(:resident).permit(:name, :age, :allergies, :medications, :next_of_kin, :nok_phone_number, :shared_room, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # Devise unthentication has been commented out as more config research is needed for controllers tests to pass.
  # To test manually, please uncomment the following line:
  # before_action :authenticate_user!

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.delete
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :capacity)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper

  def shared_room?(resident)
    if resident.shared_room
      'Yes'
    else
      'No'
    end
  end

  def assigned_room?(resident)
    if resident.room
      "#{resident.room.number}"
    else
      'Not assigned'
    end
  end

  def select_options(rooms)
    if rooms
      rooms.map { |f| f.number }
    else
      'No rooms available'
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  # TODO At the moment, assigning a room to a resident does not take into consideration room.capacity. Validation needed.
  #      Create function that does the incrementing and updates the db (not sure how to do so w/ Rails - research needed!)
  #      The room should have a residents variable in it as it needs to know both its capacity and how many residents are in it.
  #
  # def add_resident(room)
  #     if room.has_capacity()
  #         room.residents += 1
  #       UPDATE DB?
  #     else
  #         "Sorry, this rooms is full"
  #    end
  # end
  #
  # def has_capacity(room)
  #     room.residents < room.capacity
  # end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Care Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="https://i.imgur.com/s2Fhk71.png" />
  </head>

  <body>
    <!-- header -->
    <% if request.path_info != '/' %>
    <header class="menu">
      <nav>
        <ul>
          <img src="https://i.imgur.com/dxCqOoa.png" alt="Care Home Logo" width="400px">
          <a href="/">Home</a>
          <a href="/residents">All Residents</a>
          <a href="/rooms">All Rooms</a>
          <a href="/residents/new">Add New Resident</a>
          <a href="/rooms/new">Add New Room</a>
          <!-- user authentication -->
          <% if current_user %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to "Log In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </ul>
      </nav>
    </header>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/residents/_form.html.erb
<%= form_with(model: resident, local: true) do |form| %>
  <% if resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
      <% resident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :required => true %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :allergies %>
    <%= form.text_field :allergies %>
  </div>

  <div class="field">
    <%= form.label :medications %>
    <%= form.text_field :medications %>
  </div>

  <div class="field">
    <%= form.label :next_of_kin %>
    <%= form.text_field :next_of_kin, :required => true %>
  </div>

  <div class="field">
    <%= form.label :nok_phone_number %>
    <%= form.text_field :nok_phone_number, :required => true %>
  </div>

  <div class="field">
    <%= form.label :shared_room %>
    <%= form.check_box :shared_room %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.select :room_id, select_options(@rooms), include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/residents/edit.html.erb
<div class="resident-container">
  <h1>Editing Resident</h1>

  <div class="row">
    <%= render 'form', resident: @resident %>
  </div>
  <%= link_to 'Show', @resident %> |
  <%= link_to 'Back', residents_path %>
</div>

app/views/residents/index.html.erb
<div class="resident-container">
  <p id="notice"><%= notice %></p>
  <h1>Residents</h1>
    <div class="row">
      <% @residents.each do |resident| %>
        <div class="col-2">
          <div class="resident">
            <p>Name: <%= resident.name %></>
            <p>Age: <%= resident.age %></>
            <p>Allergies: <%= resident.allergies %></>
            <p>Medications: <%= resident.medications %></>
            <p>Next of Kin: <%= resident.next_of_kin %></>
            <p>NOK phone number: <%= resident.nok_phone_number %></>
            <p>Shared room: <%= shared_room?(resident) %></>
            <p>Room: <%= assigned_room?(resident) %></><br></br>
            <td><%= link_to 'Show', resident %></td>
            <td><%= link_to 'Edit', edit_resident_path(resident) %></td>
            <td><%= link_to 'Delete', resident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/residents/new.html.erb
<div class="resident-container">
  <h1>New Resident</h1>

  <div class="row">
    <%= render 'form', resident: @resident %>
  </div>
 <%= link_to 'Back', residents_path %>
</div>

app/views/residents/show.html.erb
<div class="resident-container">
  <p id="notice"><%= notice %></p>
  <h1> <%= @resident.name %> </h1>

  <div class="row">
   <div class="col-1">
     <div class="resident">
        <p>
          <strong>Age:</strong>
          <%= @resident.age %>
        </p>

        <p>
          <strong>Allergies:</strong>
          <%= @resident.allergies %>
        </p>

        <p>
          <strong>Medications:</strong>
          <%= @resident.medications %>
        </p>

        <p>
          <strong>Next of kin:</strong>
          <%= @resident.next_of_kin %>
        </p>

        <p>
          <strong>Nok phone number:</strong>
          <%= @resident.nok_phone_number %>
        </p>

        <p>
          <strong>Shared room:</strong>
          <td><%= shared_room?(@resident) %></td>
        </p>

        <p>
          <strong>Room:</strong>
          <td><%= assigned_room?(@resident) %></td>
        </p>
      </div>
    </div>
  </div>
  <%= link_to 'Edit', edit_resident_path(@resident) %> |
  <%= link_to 'Back', residents_path %>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, :required => true %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="room-container">
  <h1>Editing Room</h1>

  <div class="row">
    <%= render 'form', room: @room %>
  </div>
 <%= link_to 'Show', @room %> |
 <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/index.html.erb
<div class="room-container">
  <p id="notice"><%= notice %></p>
  <h1>Rooms</h1>
    <div class="row">
      <% @rooms.each do |room| %>
        <div class="col-2">
          <div class="room">
            <p>Number: <%= room.number %></>
            <p>Capacity: <%= room.capacity %></><br><br>
            <td><%= link_to 'Show', room %></td>
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="room-container">
  <h1>New Room</h1>

  <div class="row">
    <%= render 'form', room: @room %>
  </div>
 <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<div class="room-container">
  <p id="notice"><%= notice %></p>
  <h1> Selected Room </h1>

  <div class="row">
   <div class="col-1">
     <div class="room">
        <p>
          <strong>Number:</strong>
          <%= @room.number %>
        </p>

        <p>
          <strong>Capacity:</strong>
          <%= @room.capacity %>
        </p>
      </div>
    </div>
  </div>
  <%= link_to 'Edit', edit_room_path(@room) %> |
  <%= link_to 'Back', rooms_path %>
</div

app/views/welcome/index.html.erb
<div class="home">
   <div class="astext">
     <span class="border">
       WELCOME
     </span>
     <p> Please <%= link_to "log in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %></p>
      <img src="https://i.imgur.com/dxCqOoa.png" alt="Care Home Logo"><br>
   </div>
 </div>